update readme
I decided to propose you to add my note, because I could see several issues like:

     AttributeError: InstagramAPI instance has no attribute 'rank_token' 

etc, most probably caused by account issues.